### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by maflcko**
Only change is a warning fix for arm

### CODE REVIEW

**Comment by maflcko** [comment]
Will need the subtree update after merge: https://github.com/bitcoin-core/bitcoin-maintainer-tools#subtree-updates

**Comment by maflcko** [comment]
For reference, the warning is:

```
  CXX      crc32c/src/crc32c_libcrc32c_a-crc32c.o
In file included from crc32c/src/crc32c.cc:11:0:
crc32c/src/./crc32c_arm64_check.h: In function ‘bool crc32c::CanUseArm64Crc32()’:
crc32c/src/./crc32c_arm64_check.h:43:37: warning: the address of ‘long unsigned int getauxval(long unsigned int)’ will never be NULL [-Waddress]
   unsigned long hwcap = (&getauxval != nullptr) ? getauxval(AT_HWCAP) : 0;
                          ~~~~~~~~~~~^~~~~~~~~~

**Comment by maflcko** [comment]
ping for merge or close

**Comment by sipa** [comment]
Code review ACK cac7ca830b4a1cd4084af08412c809c4b363f3da

**Pull request merged**
